name: CI

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    runs-on: ubuntu-16.04 #target the oldest version supported
    steps:
      - uses: actions/checkout@v2
      - name: Update APT
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get install --assume-yes liblua5.1-0-dev lua5.1-0 cmake
      - name: Build Library
        run: |
          mkdir build &&
          cd build &&
          cmake ../ &&
          make
      - name: Run Tests
        run: |
          cd tests
          lua extralib/fennel run.fnl
      - name: Artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: sample.so
          path: build/sample.so
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [Win32, x64]
    steps:
      - uses: actions/checkout@v2
      - uses: xpol/setup-lua@v0.2
        with:
          lua-version: "5.1.5"
      - name: Configure
        shell: cmd
        env:
          PLATFORM: ${{ matrix.platform }}
        run: cmake -Bbuild -T v142 -A %PLATFORM% -DCMAKE_INSTALL_PREFIX=%CD%\install
      - name: Install
        shell: cmd
        run: cmake --build build --config Release --target install -j2
