name: CI

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    runs-on: ubuntu-16.04 #target the oldest version supported
    steps:
      - uses: actions/checkout@v2
      - name: Update APT
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get install --assume-yes liblua5.1-0-dev lua5.1
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build
      - name: Run Tests
          lua5.1 tests/extralib/fennel tests/run.fnl
      - name: Artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: sample.so
          path: build/sample.so
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xpol/setup-lua@v0.2
        with:
          lua-version: "luajit-2.1.0-beta3"
      - name: Configure
        run: cmake -Bbuild -G Xcode
      - name: Install
        run: cmake --build build --config Release -j2
      - name: Artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: sample.dylib
          path: build/Release/sample.dylib
  # windows:
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       platform: [Win32, x64]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: xpol/setup-lua@v0.2
  #       with:
  #         lua-version: "5.1.5"
  #     - name: Configure
  #       shell: cmd
  #       env:
  #         PLATFORM: ${{ matrix.platform }}
  #       run: cmake -Bbuild -T v142 -A %PLATFORM%
  #     - name: Install
  #       shell: cmd
  #       run: cmake --build build --config Release -j2
  #     - name: Artifact
  #       uses: actions/upload-artifact@v2-preview
  #       with:
  #         name: sample.dll
  #         path: build/Release/sample.dll